#!/usr/bin/env python3
"""Watch explicit owned Slurm IDs; queue one labeled completion event to Codex.

This watcher does not collect science, email, resume a second agent, or touch jobs.
The receipt distinguishes enqueue acknowledgement from actual root consumption.
"""
import argparse
import datetime as dt
import fcntl
import json
from pathlib import Path
import subprocess
import time

TERMINAL = {'COMPLETED', 'FAILED', 'CANCELLED', 'TIMEOUT', 'OUT_OF_MEMORY',
            'NODE_FAIL', 'BOOT_FAIL', 'DEADLINE', 'PREEMPTED', 'REVOKED'}

def stamp():
    return dt.datetime.now(dt.timezone.utc).isoformat()

def write(path, data):
    tmp = path.with_suffix(path.suffix + '.tmp')
    tmp.write_text(json.dumps(data, indent=2) + '\n')
    tmp.replace(path)

def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--jobs', nargs='+', required=True)
    p.add_argument('--thread', required=True)
    p.add_argument('--codex', required=True)
    p.add_argument('--receipt', type=Path, required=True)
    p.add_argument('--event', required=True)
    p.add_argument('--interval', type=float, default=15)
    a = p.parse_args()
    if a.interval < 1 or not all(j.isdecimal() for j in a.jobs):
        p.error('positive numeric Slurm IDs and interval >= 1 required')
    a.receipt.parent.mkdir(parents=True, exist_ok=True)
    with a.receipt.with_suffix('.lock').open('a') as lock:
        fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        if a.receipt.exists():
            old = json.loads(a.receipt.read_text())
            if any(old.get(k) != v for k, v in {'jobs': a.jobs, 'thread': a.thread, 'event': a.event}.items()):
                raise SystemExit('Receipt identity differs; use the correct existing receipt or a distinct new path.')
            if old.get('status') == 'enqueue_pending':
                raise SystemExit('Prior enqueue outcome uncertain; inspect Codex queue before manual recovery. No automatic duplicate sent.')
            if old.get('status') == 'queued':
                print('Already queued; refusing duplicate notification', flush=True)
                return
        result = {'schema': 1, 'event': a.event, 'jobs': a.jobs,
                  'thread': a.thread, 'codex': a.codex, 'started_utc': stamp(),
                  'status': 'watching', 'delivery_confirmed': False}
        write(a.receipt, result)
        while True:
            try:
                proc = subprocess.run(['sacct', '-n', '-P', '-j', ','.join(a.jobs),
                    '--format=JobIDRaw,State,ExitCode,Start,End,ElapsedRaw,AllocCPUS,NodeList'],
                    capture_output=True, text=True, timeout=30)
            except (subprocess.TimeoutExpired,OSError) as exc:
                result['last_checked_utc']=stamp()
                result['last_query_error']=str(exc)
                write(a.receipt,result)
                time.sleep(a.interval)
                continue
            records = {}
            if proc.returncode == 0:
                for line in proc.stdout.splitlines():
                    fields = line.split('|')
                    if len(fields) >= 8 and fields[0] in a.jobs:
                        records[fields[0]] = dict(zip(['job_id', 'state', 'exit_code',
                            'start', 'end', 'elapsed_seconds', 'allocated_cpus', 'nodes'], fields[:8]))
            result['last_checked_utc'] = stamp()
            result['records'] = records
            result['last_query_error'] = proc.stderr if proc.returncode else None
            write(a.receipt, result)
            if len(records) == len(a.jobs) and all(r['state'].split()[0].rstrip('+') in TERMINAL for r in records.values()):
                break
            time.sleep(a.interval)
        result['terminal_seen_utc'] = stamp()
        message = ('[AUTOMATED SLURM COMPLETION EVENT; not a human message]\n'
                   f'Event: {a.event}\nReceipt: {a.receipt.resolve()}\n'
                   + '\n'.join(f"Job {r['job_id']}: {r['state']} exit={r['exit_code']}; "
                               f"elapsed={r['elapsed_seconds']}s; allocatedCPUs={r['allocated_cpus']}"
                               for r in records.values())
                   + '\nThis event is generated by the user-authorized completion watcher. '
                   'Read the receipt, acknowledge this event, and continue only the authorized task. '
                   'For notification tests, keep scientific work paused until the wake repair is verified.')
        result['message'] = message
        result['status'] = 'enqueue_pending'
        write(a.receipt, result)
        proc = subprocess.run([a.codex, 'queue', '--thread', a.thread, '--message', message],
                              capture_output=True, text=True, timeout=60)
        result['enqueue_utc'] = stamp()
        result['enqueue_exit_code'] = proc.returncode
        result['enqueue_stdout'] = proc.stdout
        result['enqueue_stderr'] = proc.stderr
        result['status'] = 'queued' if proc.returncode == 0 else 'enqueue_failed'
        write(a.receipt, result)
        print(json.dumps(result), flush=True)
        if proc.returncode:
            raise SystemExit(proc.returncode)

if __name__ == '__main__':
    main()
