"""Plot all measured torsion profiles; missing contributions stay missing."""
import argparse
from pathlib import Path
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from affordable_common import read_json, record, write_new


def render(result, output):
    data = read_json(result); out = Path(output); out.mkdir(parents=True, exist_ok=False)
    profiles = data['profiles']
    cases = ['1H4I', '4MAE', 'PQQSEQ_83440678cbbd658047c9', 'PQQSEQ_07ab500e3df76b30d71c']
    titles = ['1H4I · known Ca class', '4MAE · known La class',
              'PLM 83440678 · prediction', 'PLM 07ab500e · prediction']
    roles = ['anchor_glutamate', 'extra_acidic_ligand_homolog']
    fig, axes = plt.subplots(2, 4, figsize=(12, 6.5), sharex=True, sharey='row', layout='constrained')
    colors = {'composite': '#20252b', 'MACE': '#3476a9', 'solvent_transfer': '#bf691b'}
    labels = {'composite': 'Composite', 'MACE': 'Native MACE', 'solvent_transfer': 'Solvent contribution'}
    for row, role in enumerate(roles):
        for col, (case, title) in enumerate(zip(cases, titles)):
            ax = axes[row, col]
            profile = next((p for p in profiles if p['case_id'] == case and p['role'] == role), None)
            if profile is None:
                ax.axis('off'); ax.text(.5, .5, 'No extra-Asp role\nin this fixed core', ha='center', transform=ax.transAxes)
                continue
            samples = sorted(profile['rows'], key=lambda r: r['angle_radian'])
            angles = [r['angle_radian'] for r in samples]
            for field in colors:
                values = []
                for sample in samples:
                    component = (sample['Ca_minus_La_work_kcal_mol'] or {}).get(field)
                    if component is None:
                        pair = [(sample['endpoints'][z].get('work_kcal_mol') or {}).get(field) for z in ('Ca', 'La')]
                        component = pair[0] - pair[1] if all(isinstance(x, (int, float)) for x in pair) else np.nan
                    values.append(component)
                ax.plot(angles, values, '-o', color=colors[field], lw=1.7, ms=4, label=labels[field])
            dft = [(r['angle_radian'], r['DFT_Ca_minus_La_work_kcal_mol']) for r in samples
                   if r['angle_radian'] != 0 and r.get('DFT_Ca_minus_La_work_kcal_mol') is not None]
            if dft:
                ax.scatter(*zip(*dft), marker='x', s=55, color='#a33160', linewidth=2, label='Native DFT')
            missing = sum(r['Ca_minus_La_work_kcal_mol'] is None for r in samples)
            if missing: ax.text(.04, .05, f'{missing} composite point unavailable', fontsize=8, transform=ax.transAxes)
            ax.axhline(0, color='#aab0b5', lw=.7); ax.axvline(0, color='#aab0b5', lw=.7)
            ax.set_title(title, fontsize=10); ax.grid(alpha=.15)
            ax.spines[['right', 'top']].set_visible(False)
            ax.set_xticks([-.4, -.2, 0, .2, .4]); ax.set_xlabel('Physical rotation (radian)')
    axes[0, 0].set_ylabel('Anchor Glu\nChange in Ca−La contrast\n(model kcal/mol)')
    axes[1, 1].set_ylabel('Extra Asp\nChange in Ca−La contrast\n(model kcal/mol)')
    axes[1, 1].tick_params(labelleft=True)
    legend = {}
    for ax in axes.flat:
        handles, labels_on_axis = ax.get_legend_handles_labels()
        legend.update(zip(labels_on_axis, handles))
    fig.legend(legend.values(), legend.keys(), loc='outside lower center', ncol=4, frameon=False)
    fig.suptitle('Does a physical donor rotation change the metal contrast?\n'
                 'Positive change is more La-like; each origin is its own zero.', fontsize=13)
    for extension in ('pdf', 'svg', 'png'):
        fig.savefig(out / ('torsion_profiles.' + extension), dpi=180)
    plt.close(fig)
    caption = ('All seven frozen physical paths are shown; lines connect the calculated samples, '
               'not additional measurements. Axes share a scale within each donor-role row. '
               'Missing composite points break the curve. These are fixed-state electronic '
               'descriptors, not binding free energies. PLM cases have no biological truth labels. '
               'DFT points appear only when available in the supplied validated collection. '
               'No new energies, thresholds or structural samples were generated by plotting.\n')
    (out / 'CAPTION.txt').write_text(caption)
    write_new(out / 'provenance.json', {'result': record(result), 'plotter': record(__file__),
              'profiles': len(profiles), 'new_scientific_calculations': 0})
    return out


if __name__ == '__main__':
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--result', required=True); p.add_argument('--output', required=True)
    print(render(**vars(p.parse_args())))
