"""Finite-system gradient assembly with both cap anchors; research only.

Input native gradients are Hartree/bohr. Output gradients are dE/dR in
kcal/mol/angstrom; forces are their negatives. No electrostatic energy is
recomputed and no QM-MM classical Coulomb term is introduced here.
"""
import argparse,copy
from pathlib import Path
import numpy as np
from affordable_common import read_json,record,verify,write_new,xyz,InvalidArtifact,BOHR_TO_A,HA_TO_KCAL
from affordable_response import read_engrad
from metal_environment_reference import read_pcgrad
from metal_environment_electronic_state import NUMBERS

FACTOR=HA_TO_KCAL/BOHR_TO_A

def target_source_id(mapping):
    s=mapping['source_site']
    return f"{s['chain']}/{s['resid']}/{s.get('insertion_code','')}/{s['name']}"

def prepare_mapping(inputs,configuration,metal):
    c=read_json(inputs);config=c['configurations'][configuration]
    mapping=read_json(verify(config['core_mapping']));env=read_json(verify(c['environment_atoms']))
    exported=read_json(verify(c['export']));physical=copy.deepcopy(read_json(verify(exported['atoms'])))
    ix={a['id']:i for i,a in enumerate(physical)}
    if len(ix)!=len(physical):raise InvalidArtifact('Duplicate physical source IDs')
    def assign(sid,el,q):
        if sid not in ix:ix[sid]=len(physical);physical.append(dict(id=sid,element=el,xyz_A=q))
        else:
            if physical[ix[sid]]['element']!=el:raise InvalidArtifact('Mapped element differs')
            physical[ix[sid]]['xyz_A']=q
    real=set();qi=sorted(m['qm_index'] for m in mapping)
    atoms=xyz(verify(config['endpoints'][metal]['xyz']))
    if qi!=list(range(len(atoms))):raise InvalidArtifact('Incomplete/duplicate QM mapping')
    for m in mapping:
        idx=m['qm_index']
        if not np.allclose(atoms[idx][1:],m['xyz_A'],atol=1e-8,rtol=0):raise InvalidArtifact('Core coordinate map differs')
        if m['kind']=='cap':continue
        sid=target_source_id(m) if m['kind']=='metal' else m['source_id']
        if sid in real:raise InvalidArtifact('Duplicate real QM source')
        real.add(sid);assign(sid,atoms[idx][0],m['xyz_A'])
    env_ids=[a['id'] for a in env]
    if len(set(env_ids))!=len(env_ids) or real&set(env_ids):raise InvalidArtifact('Duplicate field or QM/field overlap')
    pc=verify(config['pointcharges']).read_text().splitlines();values=np.array([[float(x) for x in s.split()] for s in pc[1:]])
    if int(pc[0])!=len(env) or values.shape!=(len(env),4):raise InvalidArtifact('Point-charge inventory differs')
    if not np.allclose(values[:,0],[a['charge_e'] for a in env],atol=1e-12,rtol=0) or not np.allclose(values[:,1:],[a['xyz_A'] for a in env],atol=1e-8,rtol=0):raise InvalidArtifact('Point-charge map differs')
    for a in env:assign(a['id'],a['element'],a['xyz_A'])
    caps=[]
    for m in mapping:
        if m['kind']!='cap':continue
        rid,oid=m['retained_source_id'],m['omitted_source_id']
        if rid not in ix or oid not in ix:raise InvalidArtifact('Cap anchor absent from physical source')
        r=np.array(physical[ix[rid]]['xyz_A']);o=np.array(physical[ix[oid]]['xyz_A']);v=o-r;dist=np.linalg.norm(v)
        if dist<=0:raise InvalidArtifact('Coincident cap anchors')
        u=v/dist;j=m['length_A']/dist*(np.eye(3)-np.outer(u,u));jr=np.eye(3)-j
        if not np.allclose(o,m['omitted_xyz_A'],atol=1e-8,rtol=0) or not np.allclose(r,m['retained_xyz_A'],atol=1e-8,rtol=0):raise InvalidArtifact('Cap anchor coordinate differs')
        if not np.allclose(r+m['length_A']*u,m['xyz_A'],atol=1e-8,rtol=0):raise InvalidArtifact('Cap coordinate not generated by declared anchors')
        if not np.allclose(j,m['jacobian_omitted'],atol=1e-12,rtol=0) or not np.allclose(jr,m['jacobian_retained'],atol=1e-12,rtol=0):raise InvalidArtifact('Cap Jacobian differs')
        caps.append(dict(qm_index=m['qm_index'],retained_index=ix[rid],omitted_index=ix[oid],jacobian_retained=jr.tolist(),jacobian_omitted=j.tolist(),retained_id=rid,omitted_id=oid))
    return dict(inputs=record(inputs),configuration=configuration,metal=metal,physical_atoms=[dict(id=a['id'],element=a['element'],xyz_A=a['xyz_A']) for a in physical],core=mapping,field=env,caps=caps,xyz=config['endpoints'][metal]['xyz'],pointcharges=config['pointcharges'])

def scatter(mapping,qm_gradient_Ha_bohr,pc_gradient_Ha_bohr):
    q=np.asarray(qm_gradient_Ha_bohr,float);p=np.asarray(pc_gradient_Ha_bohr,float)
    if q.shape!=(len(mapping['core']),3) or p.shape!=(len(mapping['field']),3) or not np.isfinite(q).all() or not np.isfinite(p).all():raise InvalidArtifact('Gradient shape/finite values invalid')
    atoms=mapping['physical_atoms'];ix={a['id']:i for i,a in enumerate(atoms)};terms={k:np.zeros((len(atoms),3)) for k in ('real_QM','cap_retained','cap_omitted','pointcharges')}
    for a in mapping['core']:
        if a['kind']=='cap':continue
        sid=target_source_id(a) if a['kind']=='metal' else a['source_id'];terms['real_QM'][ix[sid]]+=q[a['qm_index']]
    for c in mapping['caps']:
        g=q[c['qm_index']]
        terms['cap_retained'][c['retained_index']]+=np.array(c['jacobian_retained']).T@g
        terms['cap_omitted'][c['omitted_index']]+=np.array(c['jacobian_omitted']).T@g
    for i,a in enumerate(mapping['field']):terms['pointcharges'][ix[a['id']]]+=p[i]
    terms={k:v*FACTOR for k,v in terms.items()};total=sum(terms.values())
    return dict(components={k:v.tolist() for k,v in terms.items()},gradient_kcal_mol_A=total.tolist(),force_kcal_mol_A=(-total).tolist(),translation_gradient_sum_kcal_mol_A=total.sum(axis=0).tolist(),mapping_translation_conservation_residual_kcal_mol_A=(total.sum(axis=0)-(q.sum(axis=0)+p.sum(axis=0))*FACTOR).tolist())

def assemble(inputs,configuration,metal,collection,task_id,classical=None):
    mp=prepare_mapping(inputs,configuration,metal);col=read_json(collection);row=col['rows'][task_id]
    if row.get('status')!='complete':raise InvalidArtifact('Electronic endpoint unavailable')
    receipt=read_json(verify(row['receipt']));manifest=read_json(verify(receipt['manifest']));task=next(t for t in manifest['tasks'] if t['task_id']==task_id)
    if task['xyz']['sha256']!=mp['xyz']['sha256'] or task['pointcharges']['sha256']!=mp['pointcharges']['sha256']:raise InvalidArtifact('Electronic receipt geometry/field does not match requested source state')
    raw=read_engrad(verify(row['engrad']));q=raw['gradient_Ha_per_bohr'];pc=read_pcgrad(verify(row['pointcharge_gradient']),len(mp['field']));ats=xyz(verify(mp['xyz']));numbers=NUMBERS
    if raw['atomic_numbers'].tolist()!=[numbers[a[0]] for a in ats] or not np.allclose(raw['coordinates_bohr']*BOHR_TO_A,[a[1:] for a in ats],rtol=0,atol=1e-6):raise InvalidArtifact('Native gradient atom/coordinate mismatch')
    if abs(raw['energy_Ha']-row['energy_hartree'])>1e-8:raise InvalidArtifact('Native gradient energy mismatch')
    if not np.allclose(q*FACTOR,row['gradient_kcal_mol_per_A'],atol=1e-10,rtol=1e-12):raise InvalidArtifact('Collection/native gradient mismatch')
    e=scatter(mp,q,pc);r=dict(protocol='finite_LanM_force_assembly_v1',inputs=record(inputs),collection=record(collection),task_id=task_id,configuration=configuration,metal=metal,electronic_protocol_id=manifest['protocol_id'],physical_atoms=mp['physical_atoms'],units='kcal/mol/angstrom',quantity='gradient=dE/dR; force=-gradient',electronic=e,classical_status='unavailable',total_gradient_kcal_mol_A=None,total_force_kcal_mol_A=None,full_hybrid_qualified=False,solvent_included=False,affinity=None,implementation=record(__file__))
    if classical is not None:add_classical(r,read_json(classical));r['classical_record']=record(classical)
    return r

def add_classical(result,classical):
    """Classical adapter uses source IDs, exact physical coordinates and gradient sign.

    Expected component gradients are already summed once by the reviewed ledger.
    No independent classical QM-MM Coulomb or induction component is accepted.
    """
    if classical.get('quantity')!='gradient' or classical.get('units')!='kcal/mol/angstrom':raise InvalidArtifact('Classical units/sign must be explicit')
    if classical.get('QM_MM_Coulomb_included') is not False or classical.get('C4_induction_included') is not False:raise InvalidArtifact('Classical electrostatic/induction exclusions must be explicit')
    ids=classical['source_ids'];q=np.asarray(classical['coordinates_A']);g=np.asarray(classical['gradient_kcal_mol_A']);physical=result['physical_atoms'];ix={sid:i for i,sid in enumerate(ids)}
    if len(ids)!=len(ix) or set(ids)!={a['id'] for a in physical} or q.shape!=g.shape or g.shape!=(len(ids),3) or not np.isfinite(g).all():raise InvalidArtifact('Classical physical inventory/gradient invalid')
    order=[ix[a['id']] for a in physical]
    if not np.allclose(q[order],[a['xyz_A'] for a in physical],atol=1e-8,rtol=0):raise InvalidArtifact('Classical/electronic physical coordinates differ')
    total=np.array(result['electronic']['gradient_kcal_mol_A'])+g[order]
    result.update(classical_status='available',classical_gradient_kcal_mol_A=g[order].tolist(),total_gradient_kcal_mol_A=total.tolist(),total_force_kcal_mol_A=(-total).tolist(),classical_ledger=classical.get('ledger'),classical_components=classical.get('components'))

def main():
    p=argparse.ArgumentParser()
    for name in ('inputs','configuration','metal','collection','task-id','output'):p.add_argument('--'+name,required=True)
    p.add_argument('--classical');a=p.parse_args();write_new(a.output,assemble(a.inputs,a.configuration,a.metal,a.collection,a.task_id,a.classical))
if __name__=='__main__':main()
